################################################################################
# configuration
################################################################################
[module.hugoVersion]
extended = false
min = "0.84.4"

[[module.mounts]]
source = "layouts/robots.txt"
target = "layouts/robots.txt"
